name: SilkyPickaxes
version: '1.0'
main: net.resolutemc.silkypickaxes.SilkyPickaxes
api-version: '1.20'
depend:
  - RoseStacker
commands:
  SilkyPickaxe:
    description: Main plugin command
    permission: SilkyPickaxes.Command.give
    aliases: sp